# You can add / remove / reorder freely.
# Every string in the array is one prompt.

prompts = [
  "Imagine a block letter ‘F’. Rotate it 90° clockwise in the plane, then spin it 180° about the vertical axis (like turning a page). Draw the result in ASCII.",
  "A point is at (2, 1, −3) in camera space. The camera is at (0, 0, 0) looking down −Z with a 90° FOV. What pixel row/column (in a 1920 × 1080 sensor) does the point project to?",
  "Slice a cube with a plane that passes through the mid-points of three mutually adjacent edges. What shape is the cross-section?",
  "Fold a square sheet along its vertical center line. Punch a hole 1 cm from the top-left corner of the folded sheet. Unfold it—where are the holes relative to the original corners?",
  "Camera at (0,0,0) looks toward +Z. Wall #1 is a 4 m × 4 m square 10 m away. Wall #2 is a 2 m × 2 m square 5 m away, centered exactly in front of Wall #1. What percent of Wall #1’s area is visible?",
  "A circular robot with radius 0.4 m must move from (0,0) to (6,0). There’s a 1 m-wide corridor whose centerline is the polyline (0,0)→(3,2)→(6,0). Can the robot stay inside the corridor the whole way?",
  "Gripper frame G is rotated 30° about X relative to robot frame R. Tool frame T is rotated 45° about Y relative to G. Give me the 3 × 3 rotation matrix from T to R.",
  "Here’s an unfolded net of six squares in a T-shape. When folded, which squares share an edge with the center square?",
  "Is the right-hand rule still valid if you swap the Y and Z axes but leave X alone? Why / why not?",
  "Object A is 15 cm away in X and 8 in away in Y. Object B is 120 mm away in X and 0.1 m in Y. Which is closer?",
  "A torus and a coffee mug are homeomorphic. Name a continuous deformation that turns the mug into the torus without tearing or gluing.",
  "You stand at (0,0,0) facing +Y. A mirror is the plane X = 3. Where will your reflection appear?",
    "A point starts at +7 cm. It slides −18 cm along the line. Where does it end up, and is it left or right of the origin?",
  "Segment A spans [−3 m, +9 m]. Segment B spans [+4 m, +15 m]. What portion (in meters and as a percent of A) do they overlap?",
  "Reflect the point x = −12 across the line x = +5. Where is the image?",
  "Car X is at 0 km heading + direction at 90 km/h. Car Y is at +300 km heading − direction at 60 km/h. When and where do they meet?",
  "Fold a 20 cm paper strip at the 14 cm mark so the ends align. After the fold, how far apart are the original 0 cm and 20 cm points?",
  "Point A is 250 mm from the origin. Point B is 1 ft to the right of A. How far (in centimeters) is B from the origin?",
  "Three points: P = −8, Q = 4, R = 10. Shift every point +13. Then sort them left→right with their new coordinates.",
  "A robot occupies an interval 0.6 m wide centered at +2 m. An obstacle is a 0.4 m interval centered at +3 m. Do they collide?",
  "Is the inequality  −2 < x ≤ 5 AND x > 3 equivalent to 3 < x ≤ 5? Explain.",
  "Starting at −7, move right in steps of 5 until you pass +20. List every landing spot and state whether each is even or odd.",
    "Two squares, each 4 cm by 4 cm, share a single corner so their interiors don’t overlap. Draw the composite outline and state its total perimeter.",
  "A right-triangle has legs 9 m and 12 m. A circle is inscribed (touching all three sides). What is the circle’s radius?",
  "Starting at (0,0), a robot walks 10 m east, then 10 m north, then 10 m west, then 10 m south. What is the net displacement, and what closed-shape was traced?",
  "Rectangle R spans (−3,−1) to (7,6). Another rectangle S is R translated by the vector (−4,−2). What are S’s corner coordinates, and how much do R and S overlap in area?",
  "A regular hexagon of side 5 cm is circumscribed by a circle. What is the circle’s radius, and what fraction of its area lies outside the hexagon?",
  "Fold a square paper 16 cm on a side along its main diagonal. Punch a hole 2 cm from the fold and 5 cm from one short edge. After unfolding, mark all hole locations.",
  "In the xy-plane, point P is (2, 5). Rotate P 120° counter-clockwise about the origin, then reflect across the x-axis. Where is P now?",
  "A 3 cm-wide path runs inside the boundary of a 20 cm × 12 cm rectangle, following the edges like an inner frame. Compute the area of the path and of the remaining central region.",
  "Two discs of radius 4 cm have centers 6 cm apart. Find the area of their intersection (the lens) to the nearest tenth of a square cm.",
  "A triangle has vertices (0, 0), (8, 0), and (3, 6). Find the coordinates of its centroid and the equation of the median from the vertex (3, 6)."
]

