on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "**.rs.gen"
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-test.yml
      - "rust-toolchain"
      - "rust-toolchain.toml"
  pull_request:
    paths:
  workflow_dispatch:
permissions: read-all
name: cargo test
jobs:
  cargotest:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.8.0
      - name: cargo test
        shell: bash
        run: |
          cargo test --all
        env:
          RUST_BACKTRACE: 1
